
import { SurveySection, QuestionType } from './types';

export const GOOGLE_SCRIPT_URL = "https://script.google.com/macros/s/AKfycbyJXK8HcKP00s2gH8vweH6pqtNS7osRUl-vsxQdSOncBEWF6CUtOa1-1Yjg8OZJQAqpiw/exec";


export const SURVEY_DATA: SurveySection[] = [
  {
    title: "SECTION 1: ABOUT YOU",
    description: "4 questions",
    questions: [
      {
        id: "q1_email",
        text: "Q1. What is your email address?",
        type: QuestionType.TEXT,
        required: true,
      },
      {
        id: "q2_division",
        text: "Q2. Which SCG/Corporate Division are you from?",
        type: QuestionType.DROPDOWN,
        required: true,
        options: [
          { value: "", label: "Select your division" },
          { value: "Comms & Marketing", label: "Comms & Marketing" },
          { value: "CIO Office", label: "CIO Office" },
          { value: "Digital Governance", label: "Digital Governance" },
          { value: "Finance", label: "Finance" },
          { value: "Internal Audit", label: "Internal Audit" },
          { value: "Legal", label: "Legal" },
          { value: "Organisational Excellence", label: "Organisational Excellence" },
          { value: "Partnerships and Engagement", label: "Partnerships and Engagement" },
          { value: "People & Organisation", label: "People & Organisation" },
          { value: "Procurement", label: "Procurement" },
          { value: "Strategy Planning & Transformation", label: "Strategy Planning & Transformation" },
          { value: "Other", label: "Other" },
        ],
      },
      {
        id: "q3_activities",
        text: "Q3. Which AI-First activities did you participate in?",
        description: "Include team name where applicable. Check all that apply.",
        type: QuestionType.CHECKBOX_WITH_TEXT,
        required: true,
        options: [
          { value: "sprint_1", label: "Sprint 1 (Aug)", hasTextInput: true, textInputLabel: "Team name (optional)" },
          { value: "sprint_2", label: "Sprint 2 (Sep)", hasTextInput: true, textInputLabel: "Team name (optional)" },
          { value: "sprint_3", label: "Sprint 3 (Oct)", hasTextInput: true, textInputLabel: "Team name (optional)" },
          { value: "weekly_clinics", label: "Weekly AI Clinics (office hours)" },
          { value: "lorong_ai_workshop", label: "Lorong AI Workshop (Aug)" },
          { value: "changi_visit", label: "Changi Airport Experiential Visit (Sep)" },
          { value: "manus_workshop", label: "Manus AI hands-on workshop (Oct)" },
          { value: "clw_showcase", label: "AI-First CLW Showcase (5 Nov)" },
          { value: "discover_showcase", label: "AI-First Discover Showcase (14 Nov)" },
          { value: "did_not_participate", label: "I didn't participate" },
          { value: "other", label: "Other" , hasTextInput: true, textInputLabel: "Please specify"},
        ],
      },
      {
        id: "q3a_hours",
        text: "Q3a. How many hours on average did you spend on AI-First activities (sprints, workshop, clinics) per week ?",
        type: QuestionType.RADIO,
        required: true,
        options: [
          { value: "1-5", label: "1-5 hours per week" },
          { value: "5-10", label: "5-10 hours per week" },
          { value: "10-20", label: "10-20 hours per week" },
          { value: "20-40", label: "20-40 hours per week" },
          { value: ">40", label: "> 40 hours per week" },
          { value: "none", label: "Did not spend time on AI-First activities" },
        ],
      },
    ],
  },
  {
    title: "SECTION 2: MINDSET SHIFTS",
    description: "4 questions",
    questions: [
      {
        id: "q4_confidence_before",
        text: "Q4. Before AI-First, how confident were you that you could build an AI solution directly (e.g., using AIBots, Pair or vibe coding)?",
        type: QuestionType.RADIO,
        required: true,
        options: [
          { value: "1", label: "1 - Not confident at all" },
          { value: "2", label: "2 - Slightly confident" },
          { value: "3", label: "3 - Moderately confident" },
          { value: "4", label: "4 - Confident" },
          { value: "5", label: "5 - Very confident" },
        ],
      },
      {
        id: "q5_confidence_now",
        text: "Q5. NOW, how confident are you that you can build an AI solution directly?",
        type: QuestionType.RADIO,
        required: true,
        options: [
          { value: "1", label: "1 - Not confident at all" },
          { value: "2", label: "2 - Slightly confident" },
          { value: "3", label: "3 - Moderately confident" },
          { value: "4", label: "4 - Confident" },
          { value: "5", label: "5 - Very confident" },
        ],
      },
      {
        id: "q6_breakthrough",
        text: "Q6. What was your biggest mindset breakthrough during the AI-First journey?",
        description: 'Example: "I realized AI isn\'t difficult—it\'s a learnable skill" or "I now see myself as someone who can build solutions"',
        type: QuestionType.TEXTAREA,
        required: true,
      },
      {
        id: "q7_transformation",
        text: "Q7. How has AI-First transformed the way you think, work and solve problems at work?",
        type: QuestionType.RADIO,
        required: true,
        options: [
          { value: "1", label: "1 - No change — I think and work the same way as before" },
          { value: "2", label: "2 - Low transformation — Small changes, beginning to shift my approach" },
          { value: "3", label: "3 - Moderate transformation — Noticeable changes in how I work" },
          { value: "4", label: "4 - High transformation — Major shift in my thinking and problem-solving" },
          { value: "5", label: "5 - Significant transformation — Fundamentally changed how I approach work using AI-First approach" },
        ],
      },
    ],
  },
  {
    title: "SECTION 3: BUILDING SOLLUTIONS IN DAYS NOT MONTHS",
    description: "3 questions",
    questions: [
        {
            id: "q8_time_before",
            text: "Q8. Before AI-First, how long would it have taken you or your team to build a solution or prototype?",
            type: QuestionType.RADIO,
            required: true,
            options: [
                { value: "1", label: "1 - Wouldn't know how — No idea where to start" },
                { value: "2", label: "2 - Months+ — Major project, 3+ months" },
                { value: "3", label: "3 - Weeks — Significant effort, 2-4 weeks" },
                { value: "4", label: "4 - Days — Quick turnaround, under a week" },
                { value: "5", label: "5 - Hours — Same day capability" },
            ],
        },
        {
            id: "q9_time_now",
            text: "Q9. NOW, how long does it take you or your team to build an AI solution or prototype?",
            type: QuestionType.RADIO,
            required: true,
            options: [
                { value: "1", label: "1 - Wouldn't know how — No idea where to start" },
                { value: "2", label: "2 - Months+ — Major project, 3+ months" },
                { value: "3", label: "3 - Weeks — Significant effort, 2-4 weeks" },
                { value: "4", label: "4 - Days — Quick turnaround, under a week" },
                { value: "5", label: "5 - Hours — Same day capability" },
            ],
        },
        {
            id: "q9a_deployed",
            text: "Q9a. Have you or your team built and deployed AI solutions?",
            type: QuestionType.CONDITIONAL_RADIO,
            required: true,
            options: [
                { value: "yes_multiple", label: "Yes, multiple solutions actively used", hasTextInput: true, textInputLabel: "Name of tool/solution" },
                { value: "yes_one", label: "Yes, one solution actively used", hasTextInput: true, textInputLabel: "Name of tool/solution" },
                { value: "prototype_only", label: "Built prototype, not yet deployed", hasTextInput: true, textInputLabel: "Name of tool/solution" },
                { value: "exploring", label: "Still exploring" },
                { value: "not_yet", label: "Not yet" },
            ],
            subQuestion: {
                id: "q9a_adoption",
                text: "Has your solution been adopted by others beyond your immediate team?",
                type: QuestionType.RADIO,
                triggerValues: ["yes_multiple", "yes_one"],
                options: [
                    { value: "yes_other_teams_division", label: "Yes, by other teams in my division" },
                    { value: "yes_other_divisions", label: "Yes, by other divisions in SCG" },
                    { value: "yes_outside_scg", label: "Yes, by teams outside SCG" },
                    { value: "piloted", label: "Being piloted by others" },
                    { value: "interest_shown", label: "Interest shown but not yet adopted" },
                    { value: "no_only_my_team", label: "No, still only used by my team" },
                    { value: "na", label: "Not applicable" },
                ],
            },
        },
    ]
  },
  {
    title: "SECTION 4: AI AUGMENTS HUMANS",
    description: "3 questions",
    questions: [
      {
        id: "q10_top_tasks",
        text: "Q10. What are the top 3 Time-Intensive Repetitive Tasks that consume MOST time in your typical work week?",
        type: QuestionType.MULTI_SELECT_CHECKBOX,
        required: true,
        limit: 3,
        options: [
          { value: "admin", label: "Admin (scheduling, coordination, staffing meeting etc)" },
          { value: "data_analysis", label: "Analyse data and/or Generate reports (weekly, monthly, quarterly)" },
          { value: "budget", label: "Budget planning and financial analysis" },
          { value: "compliance", label: "Compliance monitoring and auditing" },
          { value: "doc_review", label: "Document Review (e.g., Policy, Legal and regulatory matters)" },
          { value: "email", label: "Email correspondence (respond to emails)" },
          { value: "meetings", label: "Meeting preparation, attendance and follow-up action" },
          { value: "recruitment", label: "Screen, Shortlist, Interview and Selection (e.g., for recruitment)" },
          { value: "performance", label: "Performance monitoring and evaluation" },
          { value: "processing_apps", label: "Processing Applications (e.g., data request, exemptions, waivers)" },
          { value: "procurement", label: "Procurement and vendor management (e.g., AOR, evaluation)" },
          { value: "stakeholder", label: "Stakeholder Engagement and Comms (internal/external users)" },
          { value: "risk", label: "Risk evaluation and impact assessment" },
          { value: "other", label: "Others (please specify)", hasTextInput: true, textInputLabel: "Please specify" },
        ],
      },
      {
        id: "q11_time_spent",
        text: "Q11. Time spent on mundane, repetitive and time-consuming work:",
        type: QuestionType.SLIDER_PAIR,
        required: true,
      },
      {
        id: "q12_how_ai_changed",
        text: "Q12. How has AI changed the way you work?",
        description: "Check all that apply.",
        type: QuestionType.GROUPED_CHECKBOX,
        required: true,
        options: [
          { value: "less_time_repetitive", label: "I spend less time on repetitive tasks", group: "Productivity" },
          { value: "complete_faster", label: "I complete work faster", group: "Productivity" },
          { value: "handle_higher_volume", label: "I can handle higher volume of work", group: "Productivity" },
          { value: "more_time_strategic", label: "I have more time for strategic/creative work", group: "Productivity" },
          { value: "higher_quality", label: "I produce higher quality outputs", group: "Work Quality & Capability" },
          { value: "tackle_new_problems", label: "I can tackle problems I couldn't before", group: "Work Quality & Capability" },
          { value: "better_decisions", label: "I make better-informed decisions", group: "Work Quality & Capability" },
          { value: "analyze_data_effectively", label: "I can analyze data more effectively", group: "Work Quality & Capability" },
          { value: "approach_problems_differently", label: "I approach problems differently", group: "Thinking & Problem-Solving" },
          { value: "experiment_more", label: "I experiment more and take more risks", group: "Thinking & Problem-Solving" },
          { value: "think_creatively", label: "I think more creatively about solutions", group: "Thinking & Problem-Solving" },
          { value: "question_traditional_ways", label: "I question traditional ways of working", group: "Thinking & Problem-Solving" },
          { value: "collaborate_differently", label: "I collaborate differently with my team", group: "Collaboration & Learning" },
          { value: "learn_faster", label: "I learn new skills faster", group: "Collaboration & Learning" },
          { value: "share_knowledge", label: "I share knowledge more effectively", group: "Collaboration & Learning" },
          { value: "work_across_divisions", label: "I work across divisions more easily", group: "Collaboration & Learning" },
          { value: "more_confident", label: "I feel more confident in my abilities", group: "Confidence & Mindset" },
          { value: "willing_to_try_new", label: "I'm more willing to try new things", group: "Confidence & Mindset" },
          { value: "see_myself_as_builder", label: "I see myself as a builder, not just a user", group: "Confidence & Mindset" },
          { value: "feel_empowered", label: "I feel more empowered in my role", group: "Confidence & Mindset" },
          { value: "redesigned_workflows", label: "I've redesigned my workflows", group: "Workflow & Tools" },
          { value: "use_different_tools", label: "I use different tools now", group: "Workflow & Tools" },
          { value: "automated_work", label: "I've automated parts of my work", group: "Workflow & Tools" },
          { value: "built_solutions_for_team", label: "I've built solutions for my team", group: "Workflow & Tools" },
          { value: "more_satisfying", label: "I find my work more satisfying", group: "Impact" },
          { value: "less_stress", label: "I feel less stressed by administrative workload", group: "Impact" },
          { value: "better_service", label: "I provide better service to stakeholders", group: "Impact" },
          { value: "upskilling", label: "I have learnt new skills I can apply in my work to solve problems", group: "Impact" },
          { value: "no_change", label: "No significant change for me yet", group: "Impact" },
          { value: "other", label: "Other", group: "Impact", hasTextInput: true, textInputLabel: "Please specify" },
        ],
      },
    ],
  },
  {
    title: "SECTION 5: WHAT WORKED & GREATEST IMPACT",
    description: "5 questions",
    questions: [
        {
            id: "q13_effectiveness",
            text: "Q13. How effective was the AI-First programme to build AI capability in SCG (3 sprints, 3 workshops, AI Clinics and closers)?",
            type: QuestionType.RADIO,
            required: true,
            options: [
                { value: "1", label: "1 - Not effective — Didn't help me learn or build" },
                { value: "2", label: "2 - Somewhat effective — Some value but limited impact" },
                { value: "3", label: "3 - Moderately effective — Good structure, helped me progress" },
                { value: "4", label: "4 - Highly effective — Strong impact on my learning and building" },
                { value: "5", label: "5 - Extremely effective — Essential to my transformation" },
                { value: "na", label: "N/A — I didn't participate in AI-First activities" },
            ],
        },
        {
            id: "q14_pain_points",
            text: "Q14. What were your main pain points or challenges during AI-First?",
            description: "Choose your top THREE pain points",
            type: QuestionType.MULTI_SELECT_CHECKBOX,
            required: true,
            limit: 3,
            options: [
                { value: "time", label: "Time constraints — Too busy with BAU work" },
                { value: "complexity", label: "Technical complexity — Steep learning curve" },
                { value: "use_cases", label: "Unclear use cases — Difficulty identifying problems to solve" },
                { value: "tool_limits", label: "Tool limitations — AI tools didn't meet my needs" },
                { value: "support", label: "Lack of support — Needed more guidance" },
                { value: "coordination", label: "Team coordination — Difficulty working with sprint team" },
                { value: "sustainability", label: "Solution sustainability — Built something but can't scale it" },
                { value: "data_access", label: "Data access — Couldn't get the data I needed" },
                { value: "governance", label: "Approval/governance — Unclear policies or slow approvals" },
                { value: "integration", label: "Integration challenges — AI doesn't work with existing systems" },
                { value: "other", label: "Other", hasTextInput: true, textInputLabel: "Please specify" },
                { value: "no_challenges", label: "I didn't face significant challenges" },
            ],
        },
        {
            id: "q15_personal_win",
            text: "Q15. What is your biggest personal win or transformation story from AI-First?",
            description: "Example: Share a specific moment, solution, or realisation that made the biggest difference for you",
            type: QuestionType.TEXTAREA,
            required: true,
        },
        {
            id: "q16_success_factors",
            text: "Q16. In your view, what were the critical success factors for AI-First?",
            description: "Example: What made it work? What enabled your success or the success you observed?",
            type: QuestionType.TEXTAREA,
            required: true,
        },
        {
            id: "q17_culture_shifts",
            text: "Q17. Have you observed any organisational culture shifts in your division because of AI-First?",
            description: "Example: Changes in how people work, collaborate, experiment, building solutions directly or think about innovation",
            type: QuestionType.TEXTAREA,
            required: true,
        },
    ]
  },
  {
    title: "SECTION 6: PHASE 2 PRIORITIES",
    description: "3 questions",
    questions: [
        {
            id: "q18_support_needed",
            text: "Q18. What support do you need most now after AI-First Phase 1 sprints are completed?",
            description: "Choose your top THREE to prioritize",
            type: QuestionType.MULTI_SELECT_CHECKBOX,
            required: true,
            limit: 3,
            options: [
                { value: "scaling", label: "Help scaling solutions to teams/divisions" },
                { value: "expert_help", label: "Expert help for troubleshooting" },
                { value: "training", label: "On-going AI training and workshops" },
                { value: "challenge", label: "Organise another 90-day challenge (sprints)" },
                { value: "community", label: "Establish SCG AI Community of Practice" },
                { value: "protected_time", label: "Protected time to experiment" },
                { value: "tool_access", label: "Better tool/platform access" },
                { value: "use_case_library", label: "Use case library and repository" },
                { value: "leadership", label: "Leadership buy-in" },
                { value: "policy", label: "Clearer AI policies and governance" },
                { value: "collaboration", label: "Cross-division collaboration" },
                { value: "templates", label: "Templates, playbooks and frameworks" },
                { value: "other", label: "Other", hasTextInput: true, textInputLabel: "Please specify" },
            ],
        },
        {
            id: "q19_blockers",
            text: "Q19. What are your biggest blockers or barriers in continuing to use AI tools?",
            description: "Choose your top THREE blockers",
            type: QuestionType.MULTI_SELECT_CHECKBOX,
            required: true,
            limit: 3,
            options: [
                { value: "time", label: "Time — Too busy to experiment or learn" },
                { value: "skills", label: "Skills gaps — Technical knowledge or prompting skills" },
                { value: "use_cases", label: "Unclear use cases — Don't know what problems AI can solve for me" },
                { value: "tool_access", label: "Tool access — Limited access to platforms or features" },
                { value: "leadership", label: "Leadership support — Lack of organizational buy-in" },
                { value: "scaling", label: "Scaling challenges — Can't move from POC to POV and Scale" },
                { value: "ongoing_support", label: "Ongoing support — Need ongoing support and help" },
                { value: "security", label: "Data security concerns — Worried about security and confidentiality" },
                { value: "trust", label: "Trust/reliability — Concerned about AI accuracy" },
                { value: "integration", label: "Integration issues — Tools don't work with existing systems" },
                { value: "policy", label: "Policy/governance — Unclear guidelines or approval processes" },
                { value: "other", label: "Other", hasTextInput: true, textInputLabel: "Please specify" },
                { value: "no_barriers", label: "I don't have significant barriers" },
            ],
        },
        {
            id: "q20_exemplary_model",
            text: "Q20. How can SCG be an exemplary AI adoption model for other public sector corporate functions?",
            description: 'Think bold: What would make other agencies say "We want what SCG has"?',
            type: QuestionType.TEXTAREA,
            required: false,
        },
    ]
  }
];
